//USERS
export const USERS_LOADING = "USERS_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const CONFIRM_ACCOUNT = 'CONFIRM_ACCOUNT';
export const CONFIRM_INVITATION_FOR_CLUB = 'CONFIRM_INVITATION_FOR_CLUB';
export const CHECK_INVITATION_FOR_CLUB = 'CHECK_INVITATION_FOR_CLUB';
export const CONFIRM_INVITATION_FOR_PROJECT='CONFIRM_INVITATION_FOR_PROJECT';
export const CHECK_INVITATION_FOR_PROJECT='CHECK_INVITATION_FOR_PROJECT';
//ERRORS
export const GET_ERRORS = 'GET_ERRORS';

// FlASH MESSAGES
export const ADD_FLASH_MESSAGE = "ADD_FLASH_MESSAGE";
export const REMOVE_FLASH_MESSAGE = "REMOVE_FLASH_MESSAGE";

//PROJECT
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const GET_PROJECT='GET_PROJECT';


//CLUB
export const CLUBS_LOADING = "CLUBS_LOADING";
export const GET_CLUBS = 'GET_CLUBS';
export const ADD_CLUB = 'ADD_CLUB';
export const DELETE_CLUB = 'DELETE_CLUB';
export const GET_CLUB='GET_CLUB';


// Layout
export const TOGGLE_SIDE_NAV='TOGGLE_SIDE_NAV';