const listUniversity = [  
    {value: 'Université de Carthage: Faculté des sciences juridiques politiques et sociales de Tunis',label: 'Université de Carthage: Faculté des sciences juridiques politiques et sociales de Tunis'},
    {value: 'Université de Carthage: Faculté des sciences de Bizerte' ,label : 'Université de Carthage: Faculté des sciences de Bizerte'},
    {value: 'Université de Carthage: Faculté des sciences économiques et de gestion de Nabeul',label : 'Université de Carthage: Faculté des sciences économiques et de gestion de Nabeul'},
    {value: 'Université de Carthage: École nationale d\'architecture et d`\'urbanisme de Tunis',label :'Université de Carthage: École nationale d\'architecture et d`\'urbanisme de Tunis'},
    {value: 'Université de Carthage: École nationale d\'ingénieurs de Bizerte' ,label:'Université de Carthage: École nationale d\'ingénieurs de Bizerte'},
    {value: 'Université de Carthage: École nationale d\'ingénieurs de Carthage',label :'Université de Carthage: École nationale d\'ingénieurs de Carthage'},
    {value: 'Université de Carthage: École polytechnique de Tunisie',label: 'Université de Carthage: École polytechnique de Tunisie'},
    {value: 'Université de Carthage: École supérieure de la statistique et de l\'analyse de l\'information',label: 'Université de Carthage: École supérieure de la statistique et de l\'analyse de l\'information'},
    {value: 'Université de Carthage: École supérieure de l\'audiovisuel et du cinéma',label: 'Université de Carthage: École supérieure de l\'audiovisuel et du cinéma'},
    {value: 'Université de Carthage: Institut préparatoire aux études d\'ingénieurs de Bizerte',label: 'Université de Carthage: Institut préparatoire aux études d\'ingénieurs de Bizerte'},
    {value: 'Université de Carthage: Institut des hautes études commerciales de Carthage',label: 'Université de Carthage: Institut des hautes études commerciales de Carthage'},
    {value: 'Université de Carthage: Institut national des sciences appliquées et de technologie',label: 'Université de Carthage: Institut national des sciences appliquées et de technologie'},
    {value: 'Université de Carthage: Institut supérieur des sciences appliquées et de technologie de Mateur',label: 'Université de Carthage: Institut supérieur des sciences appliquées et de technologie de Mateur'},
    {value: 'Université de Carthage: Institut préparatoire aux études d\'ingénieurs de Nabeul',label: 'Université de Carthage: Institut préparatoire aux études d\'ingénieurs de Nabeul'},
    {value: 'Université de Carthage: Institut préparatoire aux études scientifiques et techniques',label: 'Université de Carthage: Institut préparatoire aux études scientifiques et techniques'},
    {value: 'Université de Carthage: Institut supérieur des beaux arts de Nabeul',label: 'Université de Carthage: Institut supérieur des beaux arts de Nabeul'},
    {value: 'Université de Carthage: Institut supérieur des technologies de l\'environnemde l\'urbanisme et du bâtiment', label: 'Université de Carthage: Institut supérieur des technologies de l\'environnemde l\'urbanisme et du bâtiment'},
    {value: 'Université de Carthage: Institut supérieur des langues de Tunis',label: 'Université de Carthage: Institut supérieur des langues de Tunis'},
    {value: 'Université de Carthage: Institut supérieur des langues appliquées et d\'informatique de Nabeul',label: 'Université de Carthage: Institut supérieur des langues appliquées et d\'informatique de Nabeul'},
    {value: 'Université de Carthage: Institut supérieur des sciences et technologies de l\'environnement de Borj Cédria',label: 'Université de Carthage: Institut supérieur des sciences et technologies de l\'environnement de Borj Cédria'},
    {value: 'Université de Carthage: Institut supérieur de commerce et de comptabilité de Bizerte',label: 'Université de Carthage: Institut supérieur de commerce et de comptabilité de Bizerte'},
    {value: 'Université de Carthage: Institut supérieur des technologies de l\'information et de la communication de Borj Cédria',label: 'Université de Carthage: Institut supérieur des technologies de l\'information et de la communication de Borj Cédria'},
    {value: 'Université de Carthage: École supérieure des communications de Tunis',label: 'Université de Carthage: École supérieure des communications de Tunis'},
    {value: 'Université de Carthage: École supérieure d\'agriculture de Mograne',label: 'Université de Carthage: École supérieure d\'agriculture de Mograne'},
    {value: 'Université de Carthage: École supérieure d\'agriculture de Mateur',label: 'Université de Carthage: École supérieure d\'agriculture de Mateur'},
    {value: 'Université de Carthage: École supérieure des industries alimentaires de Tunis',label: 'Université de Carthage: École supérieure des industries alimentaires de Tunis'},
    {value: 'Université de Carthage: Institut supérieur de pêche et d\'aquaculture de Bizerte',label: 'Université de Carthage: Institut supérieur de pêche et d\'aquaculture de Bizerte'},
    {value: 'Université de Carthage: Institut national du travail et des études sociales',label: 'Université de Carthage: Institut national du travail et des études sociales'},
    {value: 'Université de Carthage: Institut supérieur des cadres de l\'enfance',label: 'Université de Carthage: Institut supérieur des cadres de l\'enfance'},
    {value: 'Université de Carthage: Institut national agronomique de Tunisie',label: 'Université de Carthage: Institut national agronomique de Tunisie'},
    {value: 'Université de Carthage: Institut des études touristiques supérieures de Sidi Dhrif',label: 'Université de Carthage: Institut des études touristiques supérieures de Sidi Dhrif'},
    {value: 'Université de Carthage: Institut préparatoire aux études biologiques et géologiques de la Soukra', label: 'Université de Carthage: Institut préparatoire aux études biologiques et géologiques de la Soukra'},
    {value: 'Université de Carthage: Institut national de recherches en génie rueaux et forêts',label: 'Université de Carthage: Institut national de recherches en génie rueaux et forêts'},
    {value: 'Université de Carthage: Institut national de recherches agronomiques de Tunis',label: 'Université de Carthage: Institut national de recherches agronomiques de Tunis'},
    {value: 'Université de La Manouba:  École supérieure des sciences et technologies du design',label: 'Université de La Manouba:  École supérieure des sciences et technologies du design'},
    {value: 'Université de La Manouba: École supérieure de commerce de Tunis',label: 'Université de La Manouba: École supérieure de commerce de Tunis'},
    {value: 'Université de La Manouba: École supérieure d\'economie numerique ',label: 'Université de La Manouba: École supérieure d\'economie numerique '},
    {value: 'Université de La Manouba: École nationale des sciences de l\'informatique',label: 'Université de La Manouba: École nationale des sciences de l\'informatique'},
    {value: 'Université de La Manouba: Institut supérieur des arts multimédia de La Manouba',label: 'Université de La Manouba: Institut supérieur des arts multimédia de La Manouba'},
    {value: 'Université de La Manouba: Institut supérieur de comptabilité et d\'administration des entreprises'},
    {value: 'Université de La Manouba: Institut supérieur de biotechnologie de Sidi Thabet'},
    {value: 'Université de La Manouba: Institut supérieur de documentation de Tunis'},
    {value: 'Université de La Manouba: Institut supérieur d\'histoire du mouvement national'},
    {value: 'Université de La Manouba: Institut de presse et des sciences de l\'information'},
    {value: 'Université de La Manouba: Faculté des lettdes arts et des humanités de La Manouba'},
    {value: 'Université de La Manouba: École nationale de médecine vétérinaire de Sidi Thabet'},
    {value: 'Université de La Manouba: Institut supérieur du sport et de l\'éducation physique de Ksar Saïd'},
    {value: 'Université de La Manouba: Institut supérieur de promotion des handicapés de Ksar Saïd'},
    {value: 'Université de Gabès: École nationale d\'ingénieurs de Gabès'},
    {value: 'Université de Gabès: Institut supérieur de sciences appliquées et de technologie de Gabès'},
    {value: 'Université de Gabès: Institut supérieur de gestion de Gabès'},
    {value: 'Université de Gabès: Institut supérieur des études technologiques de Djerba'},
    {value: 'Université de Gabès: Institut supérieur des langues de Gabès'},
    {value: 'Université de Gabès: Institut supérieur des arts et métiers de Gabès'},
    {value: 'Université de Gabès: Institut supérieur d\'informatique et de multimédia de Gabès'},
    {value: 'Université de Gabès: Institut supérieur des études juridiques de Gabès'},
    {value: 'Université de Gabès: Institut supérieur de biologie appliquée de Médenine'},
    {value: 'Université de Gabès: Institut supérieur des systèmes industriels de Gabès'},
    {value: 'Université de Gabès: Institut supérieur des sciences et techniques des eaux de Gabès'},
    {value: 'Université de Gabès: Institut supérieur des études appliquées en humanités de Médenine'},
    {value: 'Université de Gabès: Institut supérieur d\'informatique de Médenine'},
    {value: 'Université de Gabès: Institut supérieur des arts et métiers de Tataouine'},
    {value: 'Université de Gabès: Institut supérieur des sciences infirmières de Gabès'},
    {value: 'Université de Gabès: Institut des régions arides de Médenine'},
    {value:'Université de Monastir: Faculté des sciences de Monastir'},
    {value:'Université de Monastir: Faculté de médecine de Monastir '},
    {value:'Université de Monastir: Faculté de médecine dentaire de Monastir '},
    {value:'Université de Monastir: Faculté de pharmacie de Monastir'},
    {value:'Université de Monastir: Faculté des sciences économiques et de gestion de Mahdia '},
    {value:'Université de Monastir: École nationale d\'ingénieurs de Monastir '},
    {value:'Université de Monastir: École supérieure des sciences et techniques de la santé de Monastir '},
    {value:'Université de Monastir: Institut supérieur de biotechnologie de Monastir '},
    {value:'Université de Monastir: Institut préparatoire aux études d\'ingénieurs de Monastir'},
    {value:'Université de Monastir: Institut supérieur d\'informatique et de mathématiques de Monastir '},
    {value:'Université de Monastir: Institut supérieur des langues appliquées aux affaires et au tourisme de Moknine'},
    {value:'Université de Monastir: Institut supérieur d\'informatique de Mahdia '},
    {value:'Université de Monastir: Institut supérieur des sciences appliquées et de technologie de Mahdia '},
    {value:'Université de Monastir: Institut supérieur d\'arts et métiers de Mahdia'},
    {value:'Université de Monastir: Institut supérieur des études appliquées en humanités de Mahdia'},
    {value:'Université de Monastir: Institut supérieur des métiers de la mode'},
    {value:'Université de Sfax: Faculté de médecine '},
    {value:'Université de Sfax: Faculté des sciences économiques et de gestion'},
    {value:'Université de Sfax: Institut de l\'olivier'},
    {value:'Université de Sfax: Institut supérieur du sport et de l\'éducation physique'},
    {value:'Université de Sfax: École supérieure des sciences et techniques de la santé'},
    {value:'Université de Sfax: Institut supérieur des sciences infirmières'},
    {value:'Université de Sfax: Institut des hautes études commerciales'},
    {value:'Université de Sfax: Institut supérieur de gestion industrielle'},
    {value:'Université de Sfax: École nationale d\'électronique et des télécommunications'},
    {value:'Université de Sfax: Institut supérieur d\'informatique et de multimédia'},
    {value:'Université de Sfax: Institut supérieur de biotechnologie'},
    {value:'Université de Sfax: École nationale d\'ingénieurs'},
    {value:'Université de Sfax: Institut préparatoire aux études d\'ingénieurs'},
    {value:'Université de Sfax: École supérieure de commerce'},
    {value:'Université de Sfax: Institut supérieur des arts et métiers'},
    {value:'Université de Sfax: Institut supérieur de musique'},
    {value:'Université de Sfax: Institut supérieur d\'administration des affaires'},
    {value:'Université de Sfax: Faculté de droit',label:'Université de Sfax: Faculté de droit'},
    {value:'Université de Sfax: Faculté des lettres et des sciences humaines',label:'Université de Sfax: Faculté des lettres et des sciences humaines'},
    {value:'Université de Gafsa:Institut supérieur des sciences et des technologies de l\'énergie de Gafsa'},
    {value:'Université de Gafsa:Institut supérieur des sciences appliquées et de technologie de Gafsa'},
    {value:'Université de Gafsa:Institut supérieur d\'arts et métiers de Gafsa'},
    {value:'Université de Gafsa:École nationale d\'ingénieurs de Gafsa'},
    {value:'Université de Gafsa:Institut supérieur des études appliquées en humanités de Tozeur'},
    {value:'Université de Gafsa:Institut supérieur d\'administration des entreprises de Gafsa'},
    {value:'Université de Gafsa:Institut préparatoire aux études d\'ingénieurs de Gafsa'},
    {value:'Université de Gafsa:Institut supérieur des sciences appliquées et de technologie de Gafsa'},
    {value:'Université de Jendouba:  Institut supérieur des sciences humaines de Jendouba'},
    {value:'Université de Jendouba: Institut supérieur de musique et de théâtre du Kef'},
    {value:'Université de Jendouba: Institut supérieur des études appliquées en humanités du Kef'},
    {value:'Université de Jendouba: Institut supérieur des langues appliquées et informatique de Béja'},
    {value:'Université de Jendouba: Institut supérieur des arts et métiers de Siliana'},
    {value:'Université de Jendouba: Institut supérieur d\'informatique du Kef'},
    {value:'Université de Jendouba: Institut supérieur de biotechnologie de Béja'},
    {value:'Université de Jendouba:Faculté des sciences juridiqéconomiques et de gestion de Jendouba'},
    {value:'Université de Jendouba:Institut sylvo-pastoral de Tabarka'},
    {value:'Université de Jendouba:Institut supérieur des sciences infirmières du Kef'},
    {value:'Université de Jendouba:Institut supérieur du sport et de l\'éducation physique du Kef'},
    {value:'Université de Jendouba:École supérieure d\'agriculture du Kef'},
    {value:'Université de Jendouba:École supérieure des ingénieurs de l\'équipement rural de Medjez el-Bab'},
    {value:'Université de Sousse: Faculté de droit et des sciences politiques '},
    {value:'Université de Sousse:Faculté de médecine ',label:'Université de Sousse:Faculté de médecine '},
    {value:'Université de Sousse:Faculté des lettres et des sciences humaines ',label:'Université de Sousse:Faculté des lettres et des sciences humaines '},
    {value:'Université de Sousse:Faculté des sciences économiques et de gestion ',label:'Université de Sousse:Faculté des sciences économiques et de gestion '},
    {value:'Université de Sousse:École supérieure d\'horticulture et d\'élevage de Chott Meriem '},
    {value:'Université de Sousse:École nationale d\'ingénieurs ',label:'Université de Sousse:École nationale d\'ingénieurs '},
    {value:'Université de Sousse:École supérieure des sciences et de la technologie (Hammam Sousse) ',label:'Université de Sousse:École supérieure des sciences et de la technologie (Hammam Sousse) '},
    {value:'Université de Sousse:École supérieure des sciences et techniques de la santé ',label:'Université de Sousse:École supérieure des sciences et techniques de la santé '},
    {value:'Université de Sousse:Institut des hautes études commerciales ',label:'Université de Sousse:Institut des hautes études commerciales '},
    {value:'Université de Sousse:Institut supérieur de finances et de fiscalité ',label:'Université de Sousse:Institut supérieur de finances et de fiscalité '},
    {value:'Université de Sousse:Institut supérieur de gestion ',label:'Université de Sousse:Institut supérieur de gestion '},
    {value:'Université de Sousse:Institut supérieur de l\'informatique et des technologies de la communication (Hammam Sousse) ',label:'Université de Sousse:Institut supérieur de l\'informatique et des technologies de la communication (Hammam Sousse) '},
    {value:'Université de Sousse:Institut supérieur de musique ',label:'Université de Sousse:Institut supérieur de musique '},
    {value:'Université de Sousse:Institut supérieur des beaux-arts ',label:'Université de Sousse:Institut supérieur des beaux-arts '},
    {value:'Université de Sousse:Institut supérieur des sciences appliquées et de technologie ',label:'Université de Sousse:Institut supérieur des sciences appliquées et de technologie '},
    {value:'Université de Sousse:Institut supérieur des sciences infirmières ',label:'Université de Sousse:Institut supérieur des sciences infirmières '},
    {value:'Université de Sousse:Institut supérieur du transport et de la logistique',label:'Université de Sousse:Institut supérieur du transport et de la logistique'},
    {value:'Université de Kairouan:Institut supérieur d\'informatique et de gestion de Kairouan',label:'Université de Kairouan:Institut supérieur d\'informatique et de gestion de Kairouan'},
    {value:'Université de Kairouan:Institut supérieur des arts et métiers de Kairouan',label:'Université de Kairouan:Institut supérieur des arts et métiers de Kairouan'},
    {value:'Université de Kairouan:Institut supérieur des arts et métiers de Kasserine',label:'Université de Kairouan:Institut supérieur des arts et métiers de Kasserine'},
    {value:'Université de Kairouan:Institut supérieur des études juridiques et politiques de Kairouan',label:'Université de Kairouan:Institut supérieur des études juridiques et politiques de Kairouan'},
    {value:'Université de Kairouan:Institut supérieur des sciences appliquées et de technologie de Kairouan',label:'Université de Kairouan:Institut supérieur des sciences appliquées et de technologie de Kairouan'},
    {value:'Université de Kairouan:Institut supérieur des sciences appliquées et de technologie de Kasserine',label:'Université de Kairouan:Institut supérieur des sciences appliquées et de technologie de Kasserine'},
    {value:'Université de Tunis :École normale supérieure',label:'Université de Tunis :École normale supérieure'},
    {value:'Université de Tunis :École supérieure des sciences économiques et commerciales ',label:'Université de Tunis :École supérieure des sciences économiques et commerciales '},
    {value:'Université de Tunis :École nationale supérieure d\'ingénieurs ',label:'Université de Tunis :École nationale supérieure d\'ingénieurs '},
    {value:'Université de Tunis :Institut supérieur de l\'éducation et de la formation continue ',label:'Université de Tunis :Institut supérieur de l\'éducation et de la formation continue '},
    {value:'Université de Tunis :Institut supérieur des études appliquées en humanités ',label:'Université de Tunis :Institut supérieur des études appliquées en humanités '},
    {value:'Université de Tunis :Institut supérieur des beaux-arts ',label:'Université de Tunis :Institut supérieur des beaux-arts '},
    {value:'Université de Tunis :Institut préparatoire aux études littéraires et de sciences humaines ',label:'Université de Tunis :Institut préparatoire aux études littéraires et de sciences humaines '},
    {value:'Université de Tunis :Institut supérieur d\'art dramatique ',label:'Université de Tunis :Institut supérieur d\'art dramatique '},
    {value:'Université de Tunis :Institut supérieur de l\'animation pour la jeunesse et la culture ',label:'Université de Tunis :Institut supérieur de l\'animation pour la jeunesse et la culture '},
    {value:'Université de Tunis :Institut supérieur de gestion ',label:'Université de Tunis :Institut supérieur de gestion '},
    {value:'Université de Tunis :Institut préparatoire aux études d\'ingénieurs ',label:'Université de Tunis :Institut préparatoire aux études d\'ingénieurs '},
    {value:'Université de Tunis :Institut supérieur de musique ',label:'Université de Tunis :Institut supérieur de musique '},
    {value:'Université de Tunis :Institut supérieur des métiers du patrimoine ',label:'Université de Tunis :Institut supérieur des métiers du patrimoine '},
    {value:'Université de Tunis :Tunis Business School',label:'Université de Tunis :Tunis Business School'}

]
export default listUniversity